#!/usr/bin/env python3
"""
原始表格 -> Delta差分 -> LZ4压缩 -> 生成 C 头文件

表格布局 (按 interpolation.h / bsp_config.h):
  当前 DAMPING_TABLE_SIZE=128, FRICTION_TABLE_SIZE=128 -> 2KB, 不需要压缩
  未来可扩展到: Friction=32768点(128KB) + Damping=32768点(128KB) = 256KB

用法:
  1. 准备 fric_table_int32.bin / damp_table_int32.bin (小端 int32 二进制)
  2. pip install lz4 numpy
  3. python gen_lz4_tables.py
  4. 生成 App/control/lz4_tables_data.h
"""

import lz4.block
import numpy as np
import struct
import zlib
import os
import sys

# ========== 用户配置区 ==========

# 如果 TABLE_SIZE 较小 (<= 4KB), 不压缩, 直接生成原始数组
# 当表格扩大到需要压缩时, 修改下面的点数
FRICTION_POINTS = 128      # 当前: 128 点 int32 = 512B
DAMPING_POINTS  = 128      # 当前: 128 点 int32 = 512B

TOTAL_POINTS    = FRICTION_POINTS + DAMPING_POINTS
TOTAL_BYTES     = TOTAL_POINTS * 4

# 输入文件 (小端 int32 二进制, 不存在则用模拟数据)
FRIC_BIN  = "fric_table_int32.bin"
DAMP_BIN  = "damp_table_int32.bin"

# 输出路径 (相对于 tools/ 目录)
OUT_H     = "../App/control/lz4_tables_data.h"

# LZ4 压缩等级 (9 = high compression, 12 = max)
COMPRESSION_LEVEL = 9

# 压缩阈值: 原始数据 > 此值才启用 LZ4 压缩 (否则直接原始数组)
COMPRESS_THRESHOLD_BYTES = 4096  # 4KB 以上才压缩

# ========== 核心函数 ==========

def delta_encode(arr: np.ndarray) -> np.ndarray:
    """差分编码: out[0]=arr[0], out[i]=arr[i]-arr[i-1]"""
    out = np.empty_like(arr)
    out[0] = arr[0]
    out[1:] = arr[1:] - arr[:-1]
    return out


def load_or_generate(filename: str, num_points: int, label: str) -> np.ndarray:
    """加载二进制文件, 不存在则生成模拟数据"""
    if os.path.exists(filename):
        data = np.fromfile(filename, dtype='<i4')
        if len(data) != num_points:
            print(f"WARNING: {filename} has {len(data)} points, expected {num_points}. Truncating/padding.")
            if len(data) > num_points:
                data = data[:num_points]
            else:
                data = np.pad(data, (0, num_points - len(data)))
        print(f"  [OK] {filename}: {len(data)} points loaded")
    else:
        print(f"  [INFO] {filename} not found, generating mock zero data ({num_points} points)")
        data = np.zeros(num_points, dtype='<i4')
    return data


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(script_dir)

    print("=" * 60)
    print("LZ4 Table Compressor for JuAo Exoskeleton")
    print("=" * 60)

    # 1. 读取/生成原始表格
    print("\n[1/4] Loading raw tables...")
    fric = load_or_generate(FRIC_BIN, FRICTION_POINTS, "Friction")
    damp = load_or_generate(DAMP_BIN, DAMPING_POINTS, "Damping")

    # 2. Delta 差分编码
    print("\n[2/4] Delta encoding...")
    fric_d = delta_encode(fric)
    damp_d = delta_encode(damp)
    raw_combined = np.concatenate([fric_d, damp_d]).tobytes()
    print(f"  Raw size (after delta): {len(raw_combined)} bytes")

    # 3. LZ4 压缩 (或直接原始数据)
    print("\n[3/4] Compressing...")
    if len(raw_combined) > COMPRESS_THRESHOLD_BYTES:
        compressed = lz4.block.compress(
            raw_combined,
            mode='high_compression',
            compression=COMPRESSION_LEVEL,
            store_size=False
        )
        ratio = len(raw_combined) / len(compressed) if len(compressed) else 0
        print(f"  Compressed: {len(compressed)} bytes ({ratio:.2f}:1)")
        use_compression = True
    else:
        print(f"  Raw data ({len(raw_combined)} B) <= {COMPRESS_THRESHOLD_BYTES} B, skipping compression")
        compressed = raw_combined  # 直接原始数据
        use_compression = False

    # 4. CRC32 校验
    crc = zlib.crc32(raw_combined) & 0xFFFFFFFF
    print(f"  CRC32: 0x{crc:08X}")

    # 5. 生成 C 头文件
    print(f"\n[4/4] Generating {OUT_H}...")
    out_path = os.path.join(script_dir, OUT_H)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    with open(out_path, 'w') as f:
        f.write("/* Auto-generated by tools/gen_lz4_tables.py - DO NOT EDIT */\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")

        f.write(f"#define LZ4_TABLES_USE_COMPRESSION  {1 if use_compression else 0}\n")
        f.write(f"#define LZ4_TABLES_ORIGINAL_SIZE    {len(raw_combined)}UL\n")
        f.write(f"#define LZ4_TABLES_COMPRESSED_SIZE  {len(compressed)}UL\n")
        f.write(f"#define LZ4_TABLES_CRC32            0x{crc:08X}UL\n")
        f.write(f"#define LZ4_TABLES_FRICTION_POINTS  {FRICTION_POINTS}\n")
        f.write(f"#define LZ4_TABLES_DAMPING_POINTS   {DAMPING_POINTS}\n\n")

        f.write("/* Table data (compressed or raw, depending on size) */\n")
        f.write("static const uint8_t lz4_tables_data[] __attribute__((section(\".rodata.lz4_tables\"))) = {\n")

        for i, b in enumerate(compressed):
            if i % 16 == 0:
                f.write("    ")
            f.write(f"0x{b:02X},")
            if i % 16 == 15:
                f.write("\n")
            elif i == len(compressed) - 1:
                f.write("\n")

        f.write("};\n")

    print(f"\n  Done: {out_path}")
    print(f"  ({len(compressed)} bytes in C array)")

    # 6. 打印摘要
    print("\n" + "=" * 60)
    print("SUMMARY:")
    print(f"  Friction:   {FRICTION_POINTS} points ({FRICTION_POINTS*4} B)")
    print(f"  Damping:    {DAMPING_POINTS} points ({DAMPING_POINTS*4} B)")
    print(f"  Total raw:  {TOTAL_BYTES} B")
    print(f"  After LZ4:  {len(compressed)} B")
    print(f"  Compression: {'ON' if use_compression else 'OFF (raw)'}")
    print(f"  CRC32:      0x{crc:08X}")
    print("=" * 60)

    return 0


if __name__ == "__main__":
    sys.exit(main())
